export type ForgeTaskType = "bugfix" | "refactor" | "feature" | "doc" | "test" | "explore" | "other";

export type ForgeTaskRecord = {
  taskId: string;
  taskType: ForgeTaskType;
  taskCommand: string;
  profileName: string;
  sessionId: string;
  createdAt: string;
  completedAt: string;
  taskCompletion: 0 | 1;
  trustMode: "local_vps" | "default";
  passAt1: 0 | 1;
  passAtK: 0 | 1;
  codexTurns: number;
  toolCalls: number;
  toolCallsByType: Record<string, number>;
  responsesCalls: number;
  toolCallParseFailures: number;
  previousResponseResumes: number;
  memoryInjectedItems: number;
  memoryInjectedBytes: number;
  memoryUsedReferences: number;
  plannerSubtasks: number;
  workerSuccessRate: number;
  coordinationFailures: number;
  blockedDangerousActions: number;
  blockedCommands: number;
  timeoutEvents: number;
  restrictedPathAttempts: number;
  totalEstimatedTokens: number;
  llmTokensIn: number;
  llmTokensOut: number;
  codexApiCost: number;
  wallClockMs: number;
  humanMinutes: number;
  testsPassed: 0 | 1;
  lintIssuesDelta: number;
  errorMessage?: string;
  metadata?: Record<string, unknown>;
};

export type ForgeWeeklySummary = {
  weekStart: string;
  groupBy: {
    taskCommand: string;
    trustMode: "local_vps" | "default" | "all";
  };
  totalTasks: number;
  completedTasks: number;
  meanTaskSuccess: number;
  completionRate: number;
  passAt1Rate: number;
  passAtKRate: number;
  averageHumanMinutes: number;
  medianTurnsUsed: number;
  meanToolCalls: number;
  meanLlmCost: number;
  averageCostPerTask: number;
  averageTurnsPerTask: number;
  averageToolCallsPerTask: number;
  errorRate: number;
};
